### ISSUE TITLE
Water leak from ceiling at the back room

### ISSUE THREAD

**Issue by valentine** [hackerspacesg/admin#13]
During periods of extremely heavy rain, water will leak from the ceiling at the back room.

![IMG_3673](https://user-images.githubusercontent.com/676061/119373784-62736c00-bceb-11eb-8a0b-d53b7060f2a9.jpeg)
![IMG_3674](https://user-images.githubusercontent.com/676061/119373792-64d5c600-bceb-11eb-9bb9-22251c76d3d2.jpeg)

**Comment by valentine** [comment]
# WhatsApp update from landlady (22 April 2021)

> [7:49 AM, 4/22/2021] Let me send MCST another chaser, the last chaser email I sent was around 2 weeks ago but so far no response
> [7:51 AM, 4/22/2021] We plan to investigate whether it’s feasible to do our own repair within our own unit without needing access to the roof
> 

# Email update from MCST (22 April 2021)

> We apologise for the delay in reply.
> 
> There is widespread pipe leaking cases in the estate where we estimate approximately 7 stretches of main rainwater downpipe leaking (from level 1 to rooftop level 5) . As the scope of work is extensive, multiple site visits with various plumbers were required. The contractors (at least 3-4 which we have contacted) have reverted on challenges to quote especially for concealed pipes like your unit's.
> 
> Given the extensive scope, we have obtained quotations for the MCST to engage a consultant to survey and supervise the replacement work of the leaking pipes.
> 
> We are also looking at other solutions such as engaging plumbers to build a new rainwater downpipe and close the existing rainwater downpipe.
> 
> Please be assured that we are trying out best to resolve this outstanding issue.
> 
> Thank you

**Comment by valentine** [comment]
# WhatsApp update from landlady (27 May 2021)
[12:22 PM, 5/27/2021] The last email I received from MCST was that they are trying to build a new rainwater downpipe & close the existing one
[12:23 PM, 5/27/2021] Have sent a request for an update

**Comment by valentine** [comment]
# Email update from MCST (3 June 2021)

> Please be informed that we are conducting an interview with 2 licensed plumbers to understand more on the scope of works that they have proposed. 
>
> Please be assured that after the meeting has ended, I will drop you another email to update on the status.
>
> Thank you.

**Comment by valentine** [comment]
# WhatsApp update from MCST (29 June 2021)

> MA has confirmed the contractor and the scope of work. We are now in the midst of drafting the letter of award

**Comment by valentine** [comment]
# Email update from MCST (1 July 2021)

> Please be informed that we have finalised the scope of works and have awarded the works to a competent contractor.
>
> The works would start by end of July 2021 and completed by end of October 2021.
>
> Once the contractor sends us their schedule, a circular will be issued to all owners and tenants so that everyone is aware of the works.
>
> Thank you.

**Comment by GIANTCRAB** [comment]
Not relevant anymore as we have shifted our unit
