### ISSUE TITLE
Front toilet: sink and shower are temporarily out of order

### ISSUE THREAD

**Issue by valentine** [hackerspacesg/admin#14]
According to @GIANTCRAB: 

Our neighbour downstairs complained that water was leaking into their toilet ceiling. The building management believes that our toilet tiles are no longer waterproofed properly, which may require renovation to fix.

The building management has shut off water to the sink and shower for now.

The toilet flushes fine, and is still usable. Users of the toilet can wash their hands in the sink at the back after.

**Comment by valentine** [comment]
Elise (Joyce's friend) has helped us fix the leaking sink and bidet, and will be replacing the corroded shower pipe tomorrow.

We will turn on the water supply for the sink (and shower) when the shower pipe is replaced as well.

Our landlord was apparently not given advice by building management to fix the toilet tiles. As the unit's tenant, we have already informed both parties.

**Comment by GIANTCRAB** [comment]
@valentine I think this can be closed
