### ISSUE TITLE
Smoking from front and back stairwell

### ISSUE THREAD

**Issue by GIANTCRAB** [hackerspacesg/admin#18]
Some members have noted that the neighbours have been smoking in both the front and back stairwells. @valentine has filed a complaint to MCST. 

![image](https://user-images.githubusercontent.com/1075708/158128087-bd408dac-d824-4776-bb21-da0c21deccce.png)

To remedy this issue, I would recommend adhesive rubber door sealers to be placed for both front and back doors. However, I am unsure about the effectiveness of these rubber door sealers in preventing the cigarette smoke from coming in.

![image](https://user-images.githubusercontent.com/1075708/158128490-27887f52-d771-4e43-8d4d-9c70da11e6fd.png)

Are there any other suggestions or recommendations to remedy this issue? Thanks!

**Comment by GIANTCRAB** [comment]
Following up from yesterday's plenum.

We have agreed to give this a try and @icedwater commented that he will check with his friends about how to go about doing this. I will assist on this matter as well.

We will follow up on this in the next plenum.

**Comment by GIANTCRAB** [comment]
Not full proof but it can help prevent most of the smoke from coming in. No issues with opening / closing of door.

Front door

![image](https://user-images.githubusercontent.com/1075708/160256497-0225c5bf-1a25-4479-b886-e235efe8a928.png)

![image](https://user-images.githubusercontent.com/1075708/160256506-a34c7769-7983-4313-9a58-24b57135ac4a.png)

Back door

![image](https://user-images.githubusercontent.com/1075708/160256516-29c008ef-b8f8-4935-9ac2-bd6b5a28a79c.png)

**Comment by valentine** [comment]
Discussion from [2022-05-24 plenum](https://docs.hackerspace.sg/plenum/2022-05-24/):

> - Huiren: source has been found
>  - Opposite neighbour at back stairwell
>  - Downstairs neighbours for front stairwell
> - Joyce @geekyjoyce72: test door sealers with Arduino and cheap sensors?
>  - May need help from our smoker members
