### ISSUE TITLE
Water leak from the ceiling of 336D

### ISSUE THREAD

**Issue by GIANTCRAB** [hackerspacesg/admin#20]
During an inspection of the 336D unit, @valentine and I discovered that there was a water leak from the ceiling of 336D unit. I have attached a screenshot of a rough floor plan where this is located at. 

![image](https://user-images.githubusercontent.com/1075708/141462476-dfa631d6-7841-4500-bdea-f31b756c3545.png)

![image](https://user-images.githubusercontent.com/1075708/141472448-f3d5dfe9-b9cf-47d0-834a-16361cb3f9c3.png)
![image832](https://user-images.githubusercontent.com/1075708/141472982-ed58f966-f748-401f-acc6-d726c4983ea0.png)

The pictures below are the photographs of the leak.

![image](https://user-images.githubusercontent.com/1075708/141462702-ecad0eca-c593-46a2-9f19-82c20e480872.png)
![image](https://user-images.githubusercontent.com/1075708/141462715-1d7e8162-9fa1-4ee9-81c2-29b1b2d22d3c.png)

This can cause formation of small puddles in the 336D unit. Please take note and avoid putting electrical equipment there. @valentine will be following up with the building management and/or land-lady on this issue.

**Comment by GIANTCRAB** [comment]
![image](https://user-images.githubusercontent.com/1075708/156074581-c34eee5d-0f45-4637-9d79-6a57a09ceacc.png)
![image](https://user-images.githubusercontent.com/1075708/156074594-0059c4cd-cd7f-4a43-ad5d-a8cb661bb930.png)

The issue has not been resolved yet and is causing some troubling issues. It may result in mold later on.

@valentine perhaps we can get an update on this please? Has building management said anything about this?

Thanks!

**Comment by valentine** [comment]
Email sent:


> One of our staff noticed earlier this week that there is still water ingress from the roof into our unit. Please see attached images.
>
> This might be unrelated to the recent rainwater pipe replacement, but I would like it if the MCST could send someone down to take a look and rectify the issue after.
>
>Thanks!

For the record, our MCST's contact email is mcst1446@gmail.com and their office number is +6562915355:
![photo_2022-03-03_09-59-43](https://user-images.githubusercontent.com/676061/156482460-a7504168-e472-4755-a8e4-e6ed21305f4b.jpg)

**Comment by GIANTCRAB** [comment]
Following up from yesterday's plenum

Remark from @geekyjoyce72 : Fire exit has an area where the paint has been damaged by the water leak


Action: we need to carry out an inkjet print test to confirm/validate that the leak is occurring. Would anyone like to volunteer to assist on this issue?

**Comment by valentine** [comment]
Discussion from [2022-05-24 plenum](https://docs.hackerspace.sg/plenum/2022-05-24/):

>- Huiren: Waiting for volunteer
>  - Val: MCST contact and office number provided, only need someone to call
>  - Design and test inkjet print to catch leak/droplet location (KH @icedwater )

**Comment by valentine** [comment]
From my understanding, this has been fixed by KGB MCST thanks to help from Sam Lai.
