### ISSUE TITLE
Holes in the front room

### ISSUE THREAD

**Issue by GIANTCRAB** [hackerspacesg/admin#22]
There are multiple holes from the outside of the window ledge that leads to the front room. These holes allow insects like mosquitoes and bugs to easily get in. These holes were left by the previous tenant and are suspected to be caused by the initial damage from drilling for the pipes of the condensers. They are also quite deep and putting putty without a proper substrate did not work.

![image](https://user-images.githubusercontent.com/1075708/158108860-5b29a4de-a992-49fb-99bd-4386b79d460c.png)
![image](https://user-images.githubusercontent.com/1075708/158108870-24158294-a665-4d96-8eb1-9562740ecbf6.png)

**Comment by GIANTCRAB** [comment]
Following up from yesterday's plenum

@valentine commented that it is quite dangerous to fix these holes as we do not have proper harness equipment or so. We will need to outsource this to professionals. @valentine will be contacting them and this issue will be followed up in the next plenum

**Comment by valentine** [comment]
Discussion from [2022-05-24 plenum](https://docs.hackerspace.sg/plenum/2022-05-24/):

> - Val: Need to get contractor (Gina?) to fix the holes, could be batched with paint job for main area
> - Val: May need to fix to mitigate air conditioning expenses

**Comment by valentine** [comment]
I patched 2 of the holes on the left side today with Benji's help, by filling the holes with a substrate made of cardboard and wet tissue first.

We hope it holds.

![photo_2022-09-15_23-33-38](https://user-images.githubusercontent.com/676061/190457293-5dde0347-f031-4b9a-95f8-206c85540be1.jpg)
![photo_2022-09-16_00-25-55](https://user-images.githubusercontent.com/676061/190457326-76e0a95f-454b-41d6-b410-b64caf1e90cf.jpg)
![photo_2022-09-16_00-25-57](https://user-images.githubusercontent.com/676061/190457349-fadc2cb7-68e2-4fcf-8638-45d2766bd83a.jpg)

**Comment by valentine** [comment]
We do not intend to do any further work on this since we will be moving out in 2.5 months.
