### ISSUE TITLE
Sockets botched?

### ISSUE THREAD

**Issue by GIANTCRAB** [hackerspacesg/admin#24]
![image](https://user-images.githubusercontent.com/1075708/158560969-30853214-9dd4-42bb-aabc-8b5c515bf67d.png)
![image](https://user-images.githubusercontent.com/1075708/158561002-f4211ab0-d698-470f-8750-6e91826f0a8f.png)

Sometimes these sockets work and power can pass through but sometimes it doesn't or something. I think it also blew the fuses of the the power strips. 

For now, I've placed a sticker label over it to prevent usage of these 2 sockets in particular.

![image](https://user-images.githubusercontent.com/1075708/158563978-4bf23919-0708-49ca-8bcb-e871e6d3bafc.png)

EDIT: I tested the "blown" fuses with a multimeter and they seem to be fine. These sockets didn't blow up the fuse so I suspect there are multiple issues and this is just a symptom.

EDIT again: This was the testing process

Plug A -> Plug A into socket A, socket B (same box as socket A), socket C (different box) -> Plug A didn't work -> change fuse of Plug A -> Plug A into socket A -> Plug A works -> turned off socket A -> Plug A into socket A -> turned on socket A -> Plug A doesn't work -> Plug A into socket C -> Plug A works -> suspect box of socket A and B not working -> test old fuse of Plug A -> old fuse of Plug A works

**Comment by valentine** [comment]
Discussion from [2022-05-24 plenum](https://docs.hackerspace.sg/plenum/2022-05-24/):

> - Joyce @geekyjoyce72: need to know why we held off on purchasing sockets

**Comment by valentine** [comment]
We do not intend to work on this any further since we will be moving out in 2.5 months.
