### ISSUE TITLE
Why is J21 banned from hackerspace telegram group for no reason? :(

### ISSUE THREAD

**Issue by J21art** [hackerspacesg/admin#33]
Why is J21 banned from hackerspace telegram group for no reason last month? :(

**Comment by icedwater** [comment]
If there was no reason before, your relentless lack of respect for people's privacy is now a valid reason. Thank you for proving us right.

**Comment by icedwater** [comment]
For completely missing the point, and for doubling down, I have recorded this in case further action needs to be taken. Of course you were not removed for no reason. But you have continued to add to the laundry list of reasons why you and people like you are not welcome in our community.

For the record, I don't know who you are, I don't care who you are, and it is your right to waste your time and energy to dig up publicly available information. I am identifiable on the internet, after all. So are some of my friends in various pictures online. But that doesn't give me the right to post their identity on other online forums without their consent, and it is this that is a gross violation of privacy.

As for the "gossip" you mention, I can't stop others from talking about you, especially if you continue to draw attention to yourself with such damaging behaviour. I do not encourage such talk, nor participate in it, and you can talk to others who you think I am "gossiping" with to verify this.

Whether whichever person is suffering from any ailment or not, is entirely your right to privately speculate, but none of your business to put on a public forum.

I don't know how and where you were brought up, but your actions and values are definitely not welcome in the Hackerspace community.

**Comment by elfgoh** [comment]
@J21art hello stranger

Those who have been at the receiving end of your communications are not thrilled that you have made them feel uncomfortable. They consider this harassment. As such, you are not welcomed here and will be banned from github for 3 months. Any attempts to circumvent the ban by creating/using other accounts to participate in github would result in a permanent ban

At the end of 3 months, I hope that you will be able to see our perspective. If you do, please drop a mail to contact AT hackerspace dot sg to remind us. If you still don't see eye to eye, then you can agree to disagree and continue your separate way in the journey of life and we wish you good health and best of luck

I would think that you don't have ill intentions, but like I mentioned, your actions are making others uncomfortable, so please kindly back off. 

IANAL, but fyi, you may be breaking the law https://singaporelegaladvice.com/law-articles/singapore-protection-harassment-act/
