### ISSUE TITLE
Hot take: Have a single repo for issues

### ISSUE THREAD

**Issue by serverwentdown** [hackerspacesg/admin#5]
- `hackerspacesg/issues`
- Contains both space and admin issues
  - `KGB`
  - `admin`
  - `old-hardware-pattern`
- Use labels and issue templates extensively
  - Template for OHP can add instructions to share to mailing list and Telegram
- Simplify "where to post problem" and "where to find problem"
- Less maintenance

**Comment by valentine** [comment]
Just transferred all issues from KGB to admin. Thanks @serverwentdown.
